theme: jekyll-theme-leap-day

url:  http://kjle.github.com                 # 博客地址

title:                                                       # 博客标题 
subtitle:                                                  # 副标题 
author:                                                   # 作者 
simple_search:  http://www.google.com.hk/search     # 搜索引擎 
description:                                                            # 关于博客的描述 
subscribe_rss:  /atom.xml                  # Rss订阅地址, 默认是  /atom.xml 
subscribe_email:                               # 提供Email订阅的地址 
email:                                              # Rss订阅的Email地址

root:  /               # 博客路径，默认是“/“，如果你打算在子目录中，记得修改这个路径 
permalink: /blog/:year/:month/:day/:title/           # 文章的固定链接形式
